def game_rules():
    print('''
RULES OF THE GAME:
~~~~~~~~~~~~~~~~~~

1.INITIALLY BOTH THE PLAYERS ARE OUT OF THE BOARD.
TO ENTER THE STARTING POINT, THAT IS ,1 , YOU NEED TO GET 1 IN THE DIE INITIALLY.
2.MOVE FORWARD THE NUMBER OF SPACES SHOWN ON THE DICE.
3.IF YOU LAND ON THE HEAD ON THE SNAKE, YOU MUST SLIDE DOWN TO THE TAIL OF THE SNAKE.
4.IF YOU LAND AT BOTTOM OF A LADDER, YOU CAN MOVE UP THE TOP OF THE LADDER.
5.THE ONE WHO REACHES 100 FIRST IS THE WINNER.
6.HIT ENTER TO ROLL THE DICE.

NOTE : AN IMAGE OF THE BOARD IS GIVEN FOR YOU FOR REFERENCE.
''')


if __name__=='__main__':
    print("File not meant for execution")
    
